const fs = require('fs');
const path = require('path');

// Get the API key from environment variable
const apiKey = process.env.GEMINI_API_KEY || 'AIzaSyDuHfYBuFgQgzCyC89mdGKltothgXpZ_HI';

// Create the config.js content
const configContent = `// Configuration file for Gemini API
// This file is automatically generated during deployment
const CONFIG = {
    GEMINI_API_KEY: '${apiKey}'
};`;

// Write the config.js file
fs.writeFileSync(path.join(__dirname, 'config.js'), configContent);

console.log('✅ Config file generated successfully');
console.log('🔑 API Key configured:', apiKey ? 'Yes' : 'No');
